dataset:
    training: news_training.p
    validation: news_validation.p
        
training:
    train_batch_size: 2
    valid_batch_size: 2
    train_epochs: 2
    learning_rate: 0.001
    seed: 42
    max_len: 512
    summary_len: 120
    scheduler: constant_schedule_with_warmup
    scheduler_warmup_steps: 800