model: 
    model_arch: t5
    device: cuda
    max_len: 120
    num_beams: 3
    repetition_penalty: 2.5
    length_penalty: 2.0
    early_stopping: True
    t5: 
        pretrained: t5-base
        tok_pretrained: t5-base
    
training:
    train_batch_size: 2
    valid_batch_size: 2
    train_epochs: 2
    learning_rate: 0.0001
    seed: 42
    max_len: 512
    summary_len: 120
    scheduler: cosine_schedule_with_warmup
    scheduler_warmup_steps: 800